version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: mongo_allocine
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  scrapy:
    build: ./scrapy_allocine
    container_name: scrapy_allocine
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DATABASE=allocine_db
      - MONGO_COLLECTION=films

volumes:
  mongo_data:
